### ISSUE TITLE
您好，有没有考虑加入CCF期刊呢？

### ISSUE THREAD

**Issue by Alobal** [ccfddl/ccf-deadlines#100]

**Comment by jacklightChen** [comment]
您好，谢谢提的建议~ 但是，根据@0x4f5da2的说法，期刊随时都可以投，似乎并没有特别的截稿日期，不知有哪些期刊会有deadline需要记录呐？

**Comment by Alobal** [comment]
噢，我想的是单纯地加入CCF期刊进来便于同时检索~和DDL无关，可能有点偏题了不好意思~

**Comment by 0x4f5da2** [comment]
> 噢，我想的是单纯地加入CCF期刊进来便于同时检索~和DDL无关，可能有点偏题了不好意思~

这样的话，可以参考https://github.com/ccfddl/ccf-deadlines/blob/main/.readme_assets/ccf_recommended.pdf
