### ISSUE TITLE
Update EMNLP deadlines please~~

### ISSUE THREAD

**Issue by AdamRain** [ccfddl/ccf-deadlines#108]
The annual Conference on Empirical Methods in Natural Language Processing (EMNLP) 2022:
https://2022.emnlp.org/calls/papers/Important-Dates

Anonymity period begins | May 24, 2022
Abstract deadline for START direct submissions | June 17, 2022
Direct paper submission deadline(long & short papers) | June 24, 2022
Submission deadline for ARR papers | July 24, 2022
Author response period | Aug 23 – Aug 29, 2022
Notification of acceptance(long & short papers) | Oct 6, 2022
Camera-ready papers due(long & short papers) | Oct 21, 2022
Workshops & Tutorials | December 7-8, 2022
Conference | December 9-11, 2022

**Comment by 0x4f5da2** [comment]
added

**Comment by jacklightChen** [comment]
Closed with [1769360](https://github.com/ccfddl/ccf-deadlines/commit/1769360e2c2f8edee5e797c88b20af4fcff1631d)
