### ISSUE TITLE
Deadline for COLING 2022

### ISSUE THREAD

**Issue by dgliu** [ccfddl/ccf-deadlines#114]
The COLING 2022 deadline appears to have adopted an incorrect time zone. 

The information on the official website shows ``Note: All deadlines are: 11:59 PM UTC-12:00''.

**Comment by jacklightChen** [comment]
Closed with [adb4ce6](https://github.com/ccfddl/ccf-deadlines/commit/adb4ce6c92ce0be363a0f03ba1fd8df72b8b80ff)
