### ISSUE TITLE
Deadline for aaai 2023

### ISSUE THREAD

**Issue by Lukangkang123** [ccfddl/ccf-deadlines#120]
The Thirty-Seventh AAAI Conference on Artificial Intelligence (AAAI-23)
https://www.aaai.org/Conferences/AAAI-23/

July 4, 2022: AAAI-23 web site open for author registration
July 11, 2022: AAAI-23 web site open for paper submission
August 8, 2022: Abstracts due at 11:59 PM UTC-12
August 15, 2022: Full papers due at 11:59 PM UTC-12

**Comment by 0x4f5da2** [comment]
Added in https://github.com/ccfddl/ccf-deadlines/commit/cf64d05be07e777380ea3bd4b90c2c652e0f3eb2 , please check if the entry is correct.

**Comment by Lukangkang123** [comment]
> Added in [cf64d05](https://github.com/ccfddl/ccf-deadlines/commit/cf64d05be07e777380ea3bd4b90c2c652e0f3eb2) , please check if the entry is correct.

It's right.

**Comment by jacklightChen** [comment]
Closed with https://github.com/ccfddl/ccf-deadlines/commit/cf64d05be07e777380ea3bd4b90c2c652e0f3eb2
