### ISSUE TITLE
能否加入会议ICLR？

### ISSUE THREAD

**Issue by hhr114** [ccfddl/ccf-deadlines#123]
您好！

感谢你们的努力，创造出这个非常有价值的工具！

请问能否加入[ICLR](https://iclr.cc/)的截止时间呢？虽然ICLR暂时未被列入CCF，但在国内外机器学习领域都有很大的影响力，国内很多高校的评定中，ICLR都是等同于CCF A的存在。

盼回复，谢谢！

**Comment by 0x4f5da2** [comment]
您好！

非常感谢您的建议！我们也非常赞同加入ICLR能够使得我们的工具帮助更多的人。

**Comment by hhr114** [comment]
> 您好！
> 
> 非常感谢您的建议！我们也非常赞同加入ICLR能够使得我们的工具帮助更多的人。

嗯嗯，那我按照示例进行PR (pull requests)?

**Comment by 0x4f5da2** [comment]
如果您想要进行相应代码的实现，您可以添加一个与ccf a、b、c相并列的新的分类
