### ISSUE TITLE
你好，可以加入ACCV吗？

### ISSUE THREAD

**Issue by songzijiang** [ccfddl/ccf-deadlines#129]
如题， ACCV属于CCF的C类会议

**Comment by jacklightChen** [comment]
Sorry for delayed reply, if you are interested to add ACCV, please refer to [README](https://github.com/ccfddl/ccf-deadlines/blob/main/README.md) and [Pull Request](https://github.com/ccfddl/ccf-deadlines/pull/4) to send a pull request ~
