### ISSUE TITLE
Daylight saving time correction

### ISSUE THREAD

**Issue by l0nl1f3** [ccfddl/ccf-deadlines#137]
Take SIGMOD as an example, 

RESEARCH PAPER SUBMISSION CYCLE A (All Deadlines are 11:59 PM Pacific Time)

should be UTC-7, the webpage shows UTC-8

**Comment by 0x4f5da2** [comment]
"Thanks for your constructive suggestions, we will consider add some logic to resolve this problem, thank you!"
---- @jacklightChen

**Comment by jacklightChen** [comment]
Yeah, this feature sounds very important, thanks for your kind advice! We may fix it later this month, and of course sending a pr is also highly welcomed~

**Comment by jacklightChen** [comment]
We now require ddl to be checked whether it is during daylight time before merge. An example of modification: https://github.com/ccfddl/ccf-deadlines/pull/190
