### ISSUE TITLE
why not pack it up as a python package?

### ISSUE THREAD

**Issue by titi2338432** [ccfddl/ccf-deadlines#180]
I am 100% sure that those who read/use these sources are all capable of coding, Python for specific.
Since nowaday a homepage is less visited even though it is in your favorites, I suggest packing it up as a python package.
Followers could simply import the package to filter/display the dataframe for his own use, other than visiting a homepage.
The codes will be more or less like :

```python
import ccfddl
ddl = ccfddl.get_latest(category=['AI','DB'], begin ='2023-01-26' , level = ['A','B'])  # a pandas dataframe
ddl # do whatever you like
```
In this way, ccfddl will stick to everyone's computer, and every day use of course.

**Comment by jacklightChen** [comment]
Yeah, I think that your suggestion makes sense and this feature sounds very useful. However, the developers of this project have limited time at present and therefore may not be able to support the implementation of this enhancement. We appreciate and welcome any form of contribution. Thank you again for your suggestion, @titi2338432 ~

**Comment by jacklightChen** [comment]
Handled by @0x4f5da2.

**Comment by 0x4f5da2** [comment]
done https://github.com/ccfddl/ccf-deadlines/tree/main/cli
