### ISSUE TITLE
It would be even better if there was a display of previous years' acceptance rate!

### ISSUE THREAD

**Issue by Aprilkaka** [ccfddl/ccf-deadlines#198]
A modest proposal :)
It would be even better if there was a display of previous years' acceptance rate!

**Comment by jacklightChen** [comment]
Thank you for your constructive feedback. While we appreciate your suggestion, obtaining reliable and consistent information on conference acceptance rates can be challenging. If we are able to identify some reliable external data sources, we will certainly consider adding this feature in the future.

**Comment by shenmeren888** [comment]
recommend the wechat app‘轻松参会’, pls see the following link,
https://blog.csdn.net/humothetrader/article/details/128953090

**Comment by jacklightChen** [comment]
Retracked in #385.
