### ISSUE TITLE
Ordering of conference dates seems weired.

### ISSUE THREAD

**Issue by fishfishfishfishfish** [ccfddl/ccf-deadlines#271]
<img width="1804" alt="image" src="https://github.com/ccfddl/ccf-deadlines/assets/17529439/3ba67e14-1b92-46f9-a61a-01252527a33c">

**Comment by jacklightChen** [comment]
@Lukangkang123 plz check~

**Comment by Lukangkang123** [comment]
The conference dates are listed directly in alphabetical order. Because most conference dates start with the month,  you can look up conferences by month. If you want to sort by year as a priority, you can sort by due date.
