### ISSUE TITLE
Wrong deadline time zone for IMWUT/Ubicomp

### ISSUE THREAD

**Issue by Sensente** [ccfddl/ccf-deadlines#338]
The deadline for IMWUT is in the time zone Eastern US Time(UTC-5), according to the official website of IMWUT, instead of UTC-12.

Screenshots:
![image](https://github.com/ccfddl/ccf-deadlines/assets/35966153/112f457d-c6e1-46b4-b753-29e836e0222d)
![image](https://github.com/ccfddl/ccf-deadlines/assets/35966153/163de3f5-ac4c-452d-aa86-dcf2aef24db0)

Support material: https://dl.acm.org/journal/imwut/author-guidelines

**Comment by jacklightChen** [comment]
Fixed in https://github.com/ccfddl/ccf-deadlines/pull/339. I simply set the time zone to UTC-5, but do not check whether it would be affected by the daylight saving time., hope the "Sunshine Protection Act" has been taken.
