### ISSUE TITLE
The deadline for ICDE 2024 is wrong?

### ISSUE THREAD

**Issue by MineRiaaa** [ccfddl/ccf-deadlines#341]
The official site says the deadline is Friday for anywhere on earth. So it should be November 24th CST instead of November 25th CST?

**Comment by jacklightChen** [comment]
We set the deadline of ICDE to 2023-11-24 23:59:59 (Anywhere on Earth), which is aligned with one presented on the official site. This timeline will be automatically transformed based on local time zone.

**Comment by jacklightChen** [comment]
Please refer to an [AoE->CST Converter](https://datetime360.com/aoe-cst-time/) for resolving your confusion.

**Comment by MineRiaaa** [comment]
Thanks a lot!
