### ISSUE TITLE
Add previous years' acceptance rate of confs

### ISSUE THREAD

**Issue by jacklightChen** [ccfddl/ccf-deadlines#385]
We plan to add the average acceptance rates from the last three years for each conference.

Materials:
https://github.com/lixin4ever/Conference-Acceptance-Rate
https://csconferences.org/
https://iacr.org/cryptodb/data/acceptance.php

Also mentioned in #198.

**Comment by leyangjin** [comment]
Strongly agree. That would be very helpful.

**Comment by dfldylan** [comment]
love it

**Comment by jacklightChen** [comment]
Move a big step forward by @Lukangkang123: #450.

**Comment by Lukangkang123** [comment]
Acceptance rates for some conferences have been added to Tabular Preview and Wechat Applet. The data is [here](https://github.com/ccfddl/ccf-deadlines/tree/main/accept_rates)

**Comment by jacklightChen** [comment]
[#479] The main website now supports track available acceptance rates in previous 3 years. The format check will be added soon.
