### ISSUE TITLE
IJCNN 2024？

### ISSUE THREAD

**Issue by KK-wang** [ccfddl/ccf-deadlines#389]
我看官网上日期更新了，但是 IJCNN 的 EDAS 上依旧是 1.16 截止，什么情况？

**Comment by jacklightChen** [comment]
@Lukangkang123

**Comment by recHoneyDog** [comment]
> @Lukangkang123 
我看到项目上显示IJCNN有一个摘要截止日期，但是我目前没有看到IEEE对于会议提交论文有一个摘要截止日期，请问这个时间有办法查证吗？感谢！

**Comment by Lukangkang123** [comment]
> > @Lukangkang123
> > 我看到项目上显示IJCNN有一个摘要截止日期，但是我目前没有看到IEEE对于会议提交论文有一个摘要截止日期，请问这个时间有办法查证吗？感谢！

这次我只是更新了全文截止日期，摘要截止日期是上次别人更新的：[https://github.com/ccfddl/ccf-deadlines/pull/371/files](https://github.com/ccfddl/ccf-deadlines/pull/371/files)。您那边可以确认下有无摘要截止日期，如果确认没有的话，可以把摘要截止日期删了

**Comment by jacklightChen** [comment]
Please refer to #390.
