### ISSUE TITLE
Ranking bug about Conference Date

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [ccfddl/ccf-deadlines#391]
Hi CCFDDLers

首先，十分感谢你们的工作。

在使用Web时，我注意到根据会议开会的时间进行排序这个功能出现了Bug（目前只能根据字符串进行排序）。该功能正确执行能够便于我关注近期的工作，因此希望某位贡献者能正确修正它（可以尝试用正则提取下日期并存储一个Date对象副本用来正确排序）。

Sincerely
@Ruiyuan-Zhang

![image](https://github.com/ccfddl/ccf-deadlines/assets/71813586/0d1ba7b6-a3b6-4b7b-9b36-a8bcfb9a1957)

**Comment by jacklightChen** [comment]
@Lukangkang123, reproducible bugs in ccfddl.top, please check~

**Comment by Ruiyuan-Zhang** [comment]
> 这个会议日期挺不规则的，格式不统一，处理出来会有点棘手。我尽量一周内完成吧

谢谢，辛苦了。

我觉得可以用一个正则项列表，能处理多少就处理多少，估计大部分是正确的，有一些脏数据。
正则项的话，直接丢给gpt让他去写就好

**Comment by Ruiyuan-Zhang** [comment]
如果数据量不是很大的话（其实大家关心的只是近三年的会议）。可以把所有数据下载下来，让gpt data处理那个模块直接一键处理文件

**Comment by Lukangkang123** [comment]
> 如果数据量不是很大的话（其实大家关心的只是近三年的会议）。可以把所有数据下载下来，让gpt data处理那个模块直接一键处理文件 之后新更新的会议就规整去写就好

感谢提供思路，我尝试一下

**Comment by Lukangkang123** [comment]
现在完成了，可以按照日期时间先后排序了

**Comment by Ruiyuan-Zhang** [comment]
牛逼，辛苦！
