### ISSUE TITLE
ICNP 2024? (Not sure about the exact ddl h:m:s

### ISSUE THREAD

**Issue by jianshuod** [ccfddl/ccf-deadlines#405]
- year: 2024
      id: icnp24
      link: https://icnp24.cs.ucr.edu/index.html
      timeline:
        - abstract_deadline: '2024-05-17 20:00:00'
          deadline: '2023-05-24 20:00:00'
      timezone: AoE
      date: October 28-31, 2024
      place: Charleroi, Belgium

**Comment by jacklightChen** [comment]
Updated ICNP 2024 with modified DDL in #406.
