### ISSUE TITLE
Siggraph Asia 2024

### ISSUE THREAD

**Issue by dfldylan** [ccfddl/ccf-deadlines#442]
siggraph asia 2024来啦 截止2024.5.20
https://asia.siggraph.org/2024/submissions/
有点忙还没来得及pr

**Comment by fkmajiji** [comment]
请问这个会议为什么是CCF-A呢，ccf名单似乎是只说非asia的是A

**Comment by leyangjin** [comment]
> 请问这个会议为什么是CCF-A呢，ccf名单似乎是只说非asia的是A

ccf没放asia确实挺奇怪的，不过应该不久的将来应该会把aisa放进去，因为计算机图形学界基本默认把sig和sig asia划等号。

**Comment by fkmajiji** [comment]
好滴发自我的移动手机在 2024年4月30日，00:21，瓜田里的猹 ***@***.***> 写道：﻿

请问这个会议为什么是CCF-A呢，ccf名单似乎是只说非asia的是A

ccf没放asia确实挺奇怪的，不过应该不久的将来应该会把aisa放进去，因为计算机图形学界基本默认把sig和sig asia划等号。
