### ISSUE TITLE
Can I import data into the calendar 📅？

### ISSUE THREAD

**Issue by xyjigsaw** [ccfddl/ccf-deadlines#47]

**Comment by kzoacn** [comment]
This project is licensed under the MIT License. So of course you can use it for personal use.

**Comment by jacklightChen** [comment]
Please feel free to reuse. And we plan to put some add-ons where you can add events to the calendar.

**Comment by xyjigsaw** [comment]
I actually mean this, thanks anyway.
![](https://i.loli.net/2021/09/09/YRQnjDCS3k5Ieli.png)

**Comment by jacklightChen** [comment]
Yeah, got it. I have put this feature into the TODO list. Thanks for your advice~
