### ISSUE TITLE
微信小程序在pc端显示异常

### ISSUE THREAD

**Issue by C188** [ccfddl/ccf-deadlines#487]
![微信图片_20240422091655](https://github.com/ccfddl/ccf-deadlines/assets/35669513/28d9f97c-d489-44e2-94cd-2cdacc1d9441)

**Comment by jacklightChen** [comment]
@Lukangkang123

**Comment by Lukangkang123** [comment]
过段时间排查一下，最近太忙了~

**Comment by Lukangkang123** [comment]
小程序PC端现已正常显示（竖屏）
<img width="311" alt="2aceee5d882471c36c557871c0aea15" src="https://github.com/ccfddl/ccf-deadlines/assets/38984189/69ef46d0-bced-4592-b8a5-7b44e1856174">
