### ISSUE TITLE
FSE (NIS) is mistaken with ESEC/FSE (TCSE_SS_PDL).

### ISSUE THREAD

**Issue by Midor1** [ccfddl/ccf-deadlines#49]
Fast Software Encryption (FSE, a security conference) is different from ACM SIGSOFT Symposium on the Foundation of Software Engineering/ European Software Engineering Conference (ESEC/FSE, a software engineering conference). Please revise `conference/SC/fse.yml` and correct the information.

**Comment by jacklightChen** [comment]
@Midor1 Thanks for pointing this out! It may occur some misbehaviors due to the same id `fse22` shared by these two conferences. We will fix that ASAP. We appreciate your contribution and helpful suggestion.

**Comment by jacklightChen** [comment]
Solved in [9e38286](https://github.com/ccfddl/ccf-deadlines/commit/9e38286432002d464ca5d262e9245c2fae10db15)

**Comment by Midor1** [comment]
Please kindly note that this issue has not been fixed yet as the core issue is from the `yaml` file.
