### ISSUE TITLE
Update ICLR?

### ISSUE THREAD

**Issue by smiles724** [ccfddl/ccf-deadlines#491]
Though ICLR is not a conference recognized by CCF, it plays a very important role in AI and representation learning. Do you mind adding this conference to your agenda?

**Comment by jacklightChen** [comment]
Hi~ We have already accepted the [tracking](https://github.com/ccfddl/ccf-deadlines/blob/main/conference/AI/iclr.yml) for ICLR in the Non-CCF section. It seems that the latest updates of ICLR have not been pulled. Feel free to [send a pull request](https://github.com/ccfddl/ccf-deadlines/pulls) to update the ICLR~
