### ISSUE TITLE
【Requirements for new features】 Adding other ranking standards

### ISSUE THREAD

**Issue by jianshuod** [ccfddl/ccf-deadlines#499]
Some universities, like Tsinghua, maintain a different ranking standard for the international conference from CCF.
Is there the possibility of supporting other ranking standards? It will make it more convenient.
Or maybe we can fork a new branch, but updating the newest conference ddls seems challenging

**Comment by ViGeng** [comment]
Just an idea: maybe the union of several lists can help us estimate the workload of multiple-list-supporting feature.

**Comment by jacklightChen** [comment]
More ranking standards have been added in [#539].
