### ISSUE TITLE
请求增加清华大学期刊列表标签

### ISSUE THREAD

**Issue by liyaooi** [ccfddl/ccf-deadlines#537]
现在很多高校不止看CCF分区，也会看[清华大学计算机学科群推荐学术会议和期刊列表（TH-CPL）](https://numbda.cs.tsinghua.edu.cn/~yuwj/TH-CPL.pdf)。主要区别是TH-CPL将ICLR和EMNLP设为了A区等。希望可以增加TH-CPL的分区标签，给予用户更多选择。谢谢！

**Comment by jacklightChen** [comment]
Please refer to [#499], we are currently estimating the merged workload.

**Comment by jacklightChen** [comment]
After extensive discussions, we plan to add the Tsinghua ranking standard in the near future. Please stay tuned~

**Comment by jacklightChen** [comment]
Related features have been added in [#539].

**Comment by jacklightChen** [comment]
The searching bar may be updated later.

**Comment by liyaooi** [comment]
> The select bar may be updated later.

Thank you sooooooooooo much for your prompt response!😄
