### ISSUE TITLE
可否考虑添加期刊的投稿截止日期？

### ISSUE THREAD

**Issue by alioth-k** [ccfddl/ccf-deadlines#649]
感谢，毕竟会议要线下参加相较于期刊多少不太方便

**Comment by jacklightChen** [comment]
Sorry for the late reply. Different from conferences, most journals do not have call paper deadlines. Therefore, this repo does not include journals. However, our [wechat applet](https://github.com/ccfddl/ccf-deadlines/blob/main/.readme_assets/applet_qrcode.jpg) maintains such info for those interested in.
