### ISSUE TITLE
yaml format error

### ISSUE THREAD

**Issue by greatbaozi001** [ccfddl/ccf-deadlines#724]
on line 6201 of https://[ccfddl.com/conference/allconf.yml](https://ccfddl.com/conference/allconf.yml)
```
yaml.parser.ParserError: expected '<document start>', but found '<block sequence start>'
  in "<unicode string>", line 6201, column 1:
    - title: CADE
    ^
```
It seems that the there is a error with indentation.

**Comment by jacklightChen** [comment]
Thank you for mentioning this issue ~
