### ISSUE TITLE
哥，网页打不开了 / bro, I can't open the website now

### ISSUE THREAD

**Issue by tian-2024** [ccfddl/ccf-deadlines#725]
![image](https://github.com/user-attachments/assets/b0968918-bcf8-4c88-8d72-b02768e9dae7)

**Comment by jacklightChen** [comment]
Thank you for mentioning this issue ~

**Comment by qiao-huan** [comment]
> ![image](https://github.com/user-attachments/assets/b0968918-bcf8-4c88-8d72-b02768e9dae7)

好好好，还整双语的是吧
