### ISSUE TITLE
is EUSIPCO a CCF-B?

### ISSUE THREAD

**Issue by IQ17** [ccfddl/ccf-deadlines#726]

**Comment by jacklightChen** [comment]
please refer to the official website: https://www.ccf.org.cn/Academic_Evaluation/By_category/

**Comment by IQ17** [comment]
I want to tell, EUSIPCO is not a CCF-B, but it is in your websit.

![image](https://github.com/user-attachments/assets/4c89b309-b7ed-45fb-a7ef-749d8d45ec06)
