### ISSUE TITLE
ICPC2022 is not shown up

### ISSUE THREAD

**Issue by wqy21** [ccfddl/ccf-deadlines#90]
ICPC2022 is not shown up in the website of demo although it exists in the folder of conference/SE.

**Comment by jacklightChen** [comment]
Resolved in [980272a](https://github.com/ccfddl/ccf-deadlines/commit/980272ac90f739717a9462b344c3aa264cc34096), thank you for your practical advice！

**Comment by wqy21** [comment]
You're welcome!
